package frc.robot.subsystems.Drive;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.util.PathPlannerLogging;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants.ShooterConstants;
import frc.robot.Constants.VisionConstants;
import frc.robot.Constants.FieldConstants.ScoringZone;
import frc.robot.subsystems.Drive.TunerConstants.TunerSwerveDrivetrain;



/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private Vision vision = new Vision();
    private Alliance allianceColor = DriverStation.getAlliance().get();
    private Field2d TheField = new Field2d();
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    // for field centric path following:
    private final SwerveRequest.ApplyFieldSpeeds m_pathApplyFieldSpeeds = new SwerveRequest.ApplyFieldSpeeds();
    // for robot centric path following
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;


    /* VISION RELATED METHODS */
    public Pose2d getPose() {
        return this.getState().Pose;
    }

    public ScoringZone getZone() {
        Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);
        if(alliance.equals(Alliance.Blue)) {
            if(0 < getPose().getX() && getPose().getX() < 3.6) {
                return ScoringZone.BLUE_HUB;
            } else {
                if(4.03 < getPose().getY()) {
                    return ScoringZone.BLUE_PASSING_2;
                } else {
                    return ScoringZone.BLUE_PASSING_1;
                }
            }
        } else {
            if(13 < getPose().getX() && getPose().getX() < 16.6) {
                return ScoringZone.RED_HUB;
            } else {
                if(4.03 < getPose().getY()) {
                    return ScoringZone.RED_PASSING_2;
                } else {
                    return ScoringZone.RED_PASSING_1;
                }
            }
        }
    }


    public boolean isInAllianceZone() {
        double xDistance = getPose().getX();
        if (allianceColor.equals(Alliance.Blue)) {
            if (xDistance > 0 && xDistance < 4) {
                return true;
            } else {
                return false;
            }
        }
        else if (allianceColor.equals(Alliance.Blue)) {
            if (xDistance > 12.53 && xDistance < 16) {
                return true;
            } else {
                return false;
            }
        } else {
            return true;
        }
    }

    public Pose2d getTurretPose() {
        Pose2d turretPose = getPose().transformBy(VisionConstants.turretToCenter);
        turretPose = turretPose.rotateAround(turretPose.getTranslation(), Rotation2d.k180deg);

        double timeOfFlight = ShooterConstants.timeOfFlightInterpolation.getPrediction(getDistanceFromHub());
        // double timeOfFlight = 0;
        double xSpeed = getState().Speeds.vxMetersPerSecond;
        double ySpeed = getState().Speeds.vyMetersPerSecond;
        double rotSpeed = getState().Speeds.omegaRadiansPerSecond;
        ChassisSpeeds fieldCentric = ChassisSpeeds.fromRobotRelativeSpeeds(xSpeed, ySpeed, rotSpeed, getCurrentTurretPose().getRotation());
        double futurePoseX = turretPose.getX() + fieldCentric.vxMetersPerSecond*timeOfFlight;
        double futurePoseY = turretPose.getY() + fieldCentric.vyMetersPerSecond*timeOfFlight;
        double futurePoseRot = turretPose.getRotation().getRadians() + fieldCentric.omegaRadiansPerSecond*timeOfFlight;
        Pose2d futurePose = new Pose2d(futurePoseX, futurePoseY, Rotation2d.fromRadians(futurePoseRot));
        // Pose2d futurePose = turretPose.plus(
        //     new Transform2d(new Translation2d(-xSpeed, -ySpeed).times(timeOfFlight),
        //     new Rotation2d(-rotSpeed).times(timeOfFlight))
        // );
        

        TheField.getObject("turret pose").setPose(turretPose);
        TheField.getObject("turret pose").setPose(futurePose);

        return futurePose;
    }

    public Translation2d getSOTFTurretAngle(String whereToAim) {

        // Current turret pose
        Pose2d turretPose = getCurrentTurretPose();

        // Hub position
        Translation2d aimingTarget;
        if (whereToAim == "hub") {
            if(DriverStation.getAlliance().get() == Alliance.Red) {
                aimingTarget = VisionConstants.RED_HUB_POSE;
            } else {
                aimingTarget = VisionConstants.BLUE_HUB_POSE;
            }
        } else if (whereToAim == "pass") {
            if(DriverStation.getAlliance().get() == Alliance.Red) {
                if(getPose().getY() > 4.03) {
                    aimingTarget = VisionConstants.RED_PASS_SPOT_1;
                } else {
                    aimingTarget = VisionConstants.RED_PASS_SPOT_2;
                }
            } else {
                if(getPose().getY() > 4.03) {
                    aimingTarget = VisionConstants.BLUE_PASS_SPOT_1;
                } else {
                    aimingTarget = VisionConstants.BLUE_PASS_SPOT_2;
                }
            }
        }
        else {
            aimingTarget = VisionConstants.RED_HUB_POSE;
        }
        

        // Vector from turret to hub
        Translation2d toTarget =
            aimingTarget.minus(turretPose.getTranslation());

        double distance = toTarget.getNorm();

        // Time of flight from your interpolation table
        double timeOfFlight =
            ShooterConstants.timeOfFlightInterpolation
                .getPrediction(distance);

        // Convert robot speeds to field relative
        // ChassisSpeeds fieldSpeeds =
        //     ChassisSpeeds.fromRobotRelativeSpeeds(
        //         getState().Speeds,
        //         getPose().getRotation()
        //     );
        ChassisSpeeds fieldSpeeds = getState().Speeds;
        // Robot translational velocity
        Translation2d robotVelocity =
            new Translation2d(
                fieldSpeeds.vxMetersPerSecond,
                fieldSpeeds.vyMetersPerSecond
            );

        // --- TRANSLATIONAL SOTF CORRECTION ---

        Translation2d translationalCorrection =
            robotVelocity.times(timeOfFlight);

       // --- ROTATIONAL SOTF CORRECTION ---

double omega = fieldSpeeds.omegaRadiansPerSecond;

Translation2d turretOffset =
    turretPose.getTranslation().minus(getPose().getTranslation());

Translation2d rotationalVelocity =
    new Translation2d(
        -omega * turretOffset.getY(),
         omega * turretOffset.getX()
    );

Translation2d rotationalCorrection =
    rotationalVelocity.times(timeOfFlight);

        // --- COMBINED CORRECTION ---

        Translation2d correctedVector =
            toTarget
                .minus(translationalCorrection)
                .minus(rotationalCorrection);

        // Final turret aim angle
        Rotation2d aimAngle = correctedVector.getAngle();

        // Debug visualization
        TheField.getObject("turret pose")
            .setPose(turretPose);

        TheField.getObject("corrected shot vector")
            .setPose(
                new Pose2d(
                    turretPose.getTranslation().plus(correctedVector),
                    aimAngle
                )
            );

        return correctedVector;
    }

//     public Rotation2d getSOTFTurretAngle() {

//     Pose2d turretPose = getCurrentTurretPose();

//     Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);

//     Translation2d realTarget =
//         alliance == Alliance.Red
//             ? VisionConstants.RED_HUB_POSE
//             : VisionConstants.BLUE_HUB_POSE;

//     Translation2d turretPos = turretPose.getTranslation();

//     // Convert robot velocity to field frame
//     ChassisSpeeds fieldSpeeds =
//         ChassisSpeeds.fromRobotRelativeSpeeds(
//             getState().Speeds,
//             getPose().getRotation()
//         );

//     Translation2d robotVelocity =
//         new Translation2d(
//             fieldSpeeds.vxMetersPerSecond,
//             fieldSpeeds.vyMetersPerSecond
//         );

//     double omega = fieldSpeeds.omegaRadiansPerSecond;

//     // turret offset from robot center
//     Translation2d turretOffset =
//         VisionConstants.turretToCenter.getTranslation();

//     // rotational velocity of turret
//     Translation2d rotationalVelocity =
//         new Translation2d(
//             -omega * turretOffset.getY(),
//              omega * turretOffset.getX()
//         );

//     Translation2d totalRobotVelocity =
//         robotVelocity.plus(rotationalVelocity);

//     Translation2d virtualTarget = realTarget;

//     // ITERATIVE SOLVE (2 passes)
//     for (int i = 0; i < 2; i++) {

//         Translation2d toTarget =
//             virtualTarget.minus(turretPos);

//         double distance = toTarget.getNorm();

//         double timeOfFlight =
//             ShooterConstants.timeOfFlightInterpolation
//                 .getPrediction(distance);

//         virtualTarget =
//             realTarget.minus(
//                 totalRobotVelocity.times(timeOfFlight)
//             );
//     }

//     Translation2d correctedVector =
//         virtualTarget.minus(turretPos);

//     Rotation2d turretAngle =
//         correctedVector.getAngle()
//             .minus(getPose().getRotation());

//     return turretAngle;
//     }

    
    public Pose2d getCurrentTurretPose() {
        Pose2d turretPose = getPose().transformBy(VisionConstants.turretToCenter);
        turretPose = turretPose.rotateAround(turretPose.getTranslation(), Rotation2d.k180deg);
        return turretPose;
    }

    public Translation2d getHub() {
        Translation2d goalLocation = 
        DriverStation.getAlliance().get() == Alliance.Red ? 
            VisionConstants.RED_HUB_POSE : 
            VisionConstants.BLUE_HUB_POSE;
        return goalLocation;
    }

    //SOTF Solution 2
    public double[] SOTFcalc() {
                // 1. LATENCY COMP
        double latency = 0.15; // Tuned constant
        Translation2d futurePos = getTurretPose().getTranslation();

        // 2. GET TARGET VECTOR
        Translation2d goalLocation = 
        DriverStation.getAlliance().get() == Alliance.Red ? 
            VisionConstants.RED_HUB_POSE : 
            VisionConstants.BLUE_HUB_POSE;

        Translation2d targetVec = goalLocation.minus(futurePos);
        double dist = targetVec.getNorm();

        // 3. CALCULATE IDEAL SHOT (Stationary)
        // Note: This returns HORIZONTAL velocity component
        double idealHorizontalSpeed = ShooterConstants.shooterSpeedInterpolation.getPrediction(getDistanceFromHub());

        // 4. VECTOR SUBTRACTION
        Translation2d robotVelVec = new Translation2d(getState().Speeds.vxMetersPerSecond, getState().Speeds.vyMetersPerSecond);
        Translation2d shotVec = targetVec.div(dist).times(idealHorizontalSpeed).minus(robotVelVec);

        // 5. CONVERT TO CONTROLS
        double turretAngle = shotVec.getAngle().getDegrees();
        double newHorizontalSpeed = shotVec.getNorm();

        // 6. SOLVE FOR NEW PITCH/RPM
        // Assuming constant total exit velocity, variable hood:
        double totalExitVelocity = 15.0; // m/s
        // Clamp to avoid domain errors if we need more speed than possible
        double ratio = Math.min(newHorizontalSpeed / totalExitVelocity, 1.0);
        double newPitch = Math.acos(ratio);

        // 7. SET OUTPUTS
        double[] outputs = {turretAngle, Math.toDegrees(newPitch), ShooterConstants.shooterSpeedInterpolation.getPrediction(dist)};
        return outputs;
        // turret.setAngle(turretAngle);
        // hood.setAngle(Math.toDegrees(newPitch));
        // shooter.setRPM(calcRPM(totalExitVelocity));

    }

    public double getDistanceFromHub() {
        double distance = Math.hypot(getXfromHub(), getYfromHub());
        return distance;
    }

    public double getXfromLocation(Pose2d target) {
        double xDistance;
        Alliance allianceColor = DriverStation.getAlliance().get();
        if(allianceColor == Alliance.Red) {
            xDistance = Math.abs(target.getX() - getCurrentTurretPose().getX());
        } else {
            xDistance = Math.abs(target.getX() - getCurrentTurretPose().getX());
        }
        return xDistance;
    }

    public double getYfromLocation(Pose2d target) {
        double yDistance;
        Alliance allianceColor = DriverStation.getAlliance().get();
        if(allianceColor == Alliance.Red) {
            yDistance = Math.abs(target.getY() - getCurrentTurretPose().getY());
        } else {
            yDistance = Math.abs(target.getY() - getCurrentTurretPose().getY());
        }
        return yDistance;
    }

    public double getXfromHub() {
        double xDistance;
        Alliance allianceColor = DriverStation.getAlliance().get();

        if(allianceColor == Alliance.Red) {
            xDistance = VisionConstants.RED_HUB_POSE.getX() - getCurrentTurretPose().getX();
        } else {
            xDistance = VisionConstants.BLUE_HUB_POSE.getX() - getCurrentTurretPose().getX();
        }
        return xDistance;
    }

    public double getYfromHub() {
        double yDistance;
        Alliance allianceColor = DriverStation.getAlliance().get();

        if(allianceColor == Alliance.Red) {
            yDistance = VisionConstants.RED_HUB_POSE.getY() - getCurrentTurretPose().getY();
        } else {
            yDistance = VisionConstants.BLUE_HUB_POSE.getY() - getCurrentTurretPose().getY();
        }
        return yDistance;
    }

    /**
     * Update the pose estimation and std devs with new vision data
     */
    public void updateVisionMeasurements() {
        var visionEst = vision.getEstimatedGlobalPose1();
        var visionEst2 = vision.getEstimatedGlobalPose2();
        var visionEst3 = vision.getEstimatedGlobalPose3();

        if (visionEst.isPresent() && visionEst2.isPresent() && visionEst3.isPresent()) {
            var estPose = vision.getPoseFromCams();
            var estStdDevs = vision.getEstimationStdDevs(estPose);
            super.addVisionMeasurement(
                    estPose,
                    Utils.fpgaToCurrentTime(visionEst.get().timestampSeconds),
                    estStdDevs);
        } else if (visionEst.isPresent() && visionEst2.isPresent()) {
            var estPose = vision.getPoseFromCams12();
            var estStdDevs = vision.getEstimationStdDevs(estPose);
            super.addVisionMeasurement(
                    estPose,
                    Utils.fpgaToCurrentTime(visionEst.get().timestampSeconds),
                    estStdDevs);
        }else if (visionEst2.isPresent() && visionEst3.isPresent()) {
            var estPose = vision.getPoseFromCams23();
            var estStdDevs = vision.getEstimationStdDevs(estPose);
            super.addVisionMeasurement(
                    estPose,
                    Utils.fpgaToCurrentTime(visionEst2.get().timestampSeconds),
                    estStdDevs);
        } else if (visionEst.isPresent() && visionEst3.isPresent()) {
            var estPose = vision.getPoseFromCams13();
            var estStdDevs = vision.getEstimationStdDevs(estPose);
            super.addVisionMeasurement(
                    estPose,
                    Utils.fpgaToCurrentTime(visionEst.get().timestampSeconds),
                    estStdDevs);
        }else if (visionEst.isPresent()) {
            visionEst.ifPresent(est -> {
                var estPose = est.estimatedPose.toPose2d();
                var estStdDevs = vision.getEstimationStdDevs(estPose);
                super.addVisionMeasurement(
                        estPose,
                        Utils.fpgaToCurrentTime(est.timestampSeconds),
                        estStdDevs);
            });
        } else if (visionEst2.isPresent()) {
            visionEst2.ifPresent(est -> {
                var estPose = est.estimatedPose.toPose2d();
                var estStdDevs = vision.getEstimationStdDevs(estPose);
                super.addVisionMeasurement(
                        estPose,
                        Utils.fpgaToCurrentTime(est.timestampSeconds),
                        estStdDevs);
            });
        } else if (visionEst3.isPresent()) {
            visionEst3.ifPresent(est -> {
                var estPose = est.estimatedPose.toPose2d();
                var estStdDevs = vision.getEstimationStdDevs(estPose);
                super.addVisionMeasurement(
                        estPose,
                        Utils.fpgaToCurrentTime(est.timestampSeconds),
                        estStdDevs);
            });
        }
    }

/* Pathplanner and CTRE Swerve config */
    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }


    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        SmartDashboard.putData("The field", TheField);
        configureAutoBuilder();
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        TheField.getObject("robot").setPose(getPose());
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}
